/* 
	* Primitive data types in JavaScript include:
    1. Numbers - Integers, floats
    2. Strings - Any data under single quote, double quote or backtick quote
    3. Booleans - true or false value
    4. Null - empty value or no value
    5. Undefined - a declared variable without a value
    6. Symbol - A unique value that can be generated by Symbol constructor
*/

const str = "hari jum'at"

const combinedStr = `${str} tanggal 11 Nov 2022`
const combinedStr2 = str + "tanggal 11 Nov 2022"

console.log(combinedStr)